#!/bin/sh

git-update-server-info

emptyrev="0000000000000000000000000000000000000000"
upstream_name="origin"

color_start="\033[45m"
color_end="\033[0m"

## Parse parameter
if ! [ -t 0 ]; then
  read -a ref
fi

oldrev=${ref[0]}
newrev=${ref[1]}
refname=${ref[2]}

#echo "oldrev = $oldrev"
#echo "newrev = $newrev"
#echo "refname = $refname"

echo -e "$color_start--------------------------------------------------$color_end"
echo -e "$color_start--- post-receive hook triggered,               ---$color_end"
echo -e "$color_start--------------------------------------------------$color_end"
echo ""

## Start
case "$refname" in
  refs/tags/*)
    echo -e "$color_start>>> Pushing tags to [$upstream_name]$color_end"
    git push $upstream_name --tags
    echo -e "$color_start>>>all done<<<$color_end"
    exit 0
    ;;
  refs/heads/*)
    IFS='/' read -ra REFNAME <<< "${ref[2]}"
    branch="${REFNAME[2]}"
    if [ "master" == "$branch" ]; then
      echo -e "$color_start*(MASTER)$color_end"
    fi

    if [ "$emptyrev" == "$newrev" ]; then
      if [ "master" == "$branch" ]; then
        echo -e >&2 "$color_start[EE] You can not delete master branch$color_end"
        exit 1
      fi
      echo -e "$color_start>>> Deleting branch($branch) to [$upstream_name]$color_end"
      git push $upstream_name :$branch
      echo -e "$color_start>>>all done<<<$color_end"
      exit 0
    fi

    if [ "$emptyrev" == "$oldrev" ]; then
      echo -e "$color_start>>>Creating new branch [$branch]$color_end"
    fi

    echo -e "$color_start>>> Pushing branch($branch) to [$upstream_name]$color_end"
    git push $upstream_name $branch
    echo -e "$color_start>>>all done<<<$color_end"
    exit 0
    ;;
  *)
    echo >&2 "*** Unknown type of update to $refname"
    exit 1
    ;;
esac
